- description: '## The Real'
  fields:
    address.street:
      description: Street corresponding to the address
      fieldPath: address.street
    address.zipcode:
      description: This is the zipcode of the address. Specified using extended form
        and limited to addresses in the United States
      fieldPath: address.zipcode
    last_sold_date:
      description: Date of the last sale date for this property
      fieldPath: last_sold_date
  name: realestate_db.sales
  platform: exasol
  urn: urn:li:dataset:(urn:li:dataPlatform:exasol,realestate_db.sales,PROD)
- description: test
  fields:
    shipment_info:
      description: Shipment info description
      fieldPath: shipment_info
    shipment_info.date:
      description: Shipment info date description
      fieldPath: shipment_info.date
    shipment_info.destination:
      description: Shipment info destination description
      fieldPath: shipment_info.destination
    shipment_info.geo_info:
      description: Shipment info geo_info description
      fieldPath: shipment_info.geo_info
    shipment_info.geo_info.lat:
      description: Shipment info geo_info lat
      fieldPath: shipment_info.geo_info.lat
    shipment_info.geo_info.lng:
      description: Shipment info geo_info lng
      fieldPath: shipment_info.geo_info.lng
    shipment_info.target:
      description: Shipment info target description
      fieldPath: shipment_info.target
  name: SampleHdfsDataset
  platform: hdfs
  urn: urn:li:dataset:(urn:li:dataPlatform:hdfs,SampleHdfsDataset,PROD)
- description: test
  fields:
    field_bar:
      description: Bar field description
      fieldPath: field_bar
    field_foo:
      description: Foo field description
      fieldPath: field_foo
  name: SampleHiveDataset
  platform: hive
  urn: urn:li:dataset:(urn:li:dataPlatform:hive,SampleHiveDataset,PROD)
- description: table containing all the users created on a single day
  fields:
    user_id:
      description: Id of the user created
      fieldPath: user_id
    user_name:
      description: Name of the user who signed up
      fieldPath: user_name
  name: fct_users_created
  platform: hive
  urn: urn:li:dataset:(urn:li:dataPlatform:hive,fct_users_created,PROD)
- description: table containing all the users deleted on a single day
  fields:
    browser_id:
      description: Cookie attached to identify the browser
      fieldPath: browser_id
    deletion_reason:
      description: Why the user chose to deactivate
      fieldPath: deletion_reason
    session_id:
      description: Cookie attached to identify the session
      fieldPath: session_id
    timestamp:
      description: Timestamp user was deleted at
      fieldPath: timestamp
    user_id:
      description: Id of the user deleted
      fieldPath: user_id
    user_name:
      description: Name of the user who was deleted
      fieldPath: user_name
  name: fct_users_deleted
  platform: hive
  urn: urn:li:dataset:(urn:li:dataPlatform:hive,fct_users_deleted,PROD)
- description: table where each row represents a single log event
  fields:
    browser:
      description: test
      fieldPath: browser
    event_data:
      description: Data of your event
      fieldPath: event_data
    event_name:
      description: Name of your logging event
      fieldPath: event_name
    timestamp:
      description: TS the event was ingested
      fieldPath: timestamp
  name: logging_events
  platform: hive
  urn: urn:li:dataset:(urn:li:dataPlatform:hive,logging_events,PROD)
- description: test
  fields:
    '[version=2.0].[key=True].[type=int].id':
      description: Id specifying which partition the message should go to
      fieldPath: '[version=2.0].[key=True].[type=int].id'
    '[version=2.0].[type=boolean].field_bar':
      description: Bar field description
      fieldPath: '[version=2.0].[type=boolean].field_bar'
    '[version=2.0].[type=boolean].field_foo_2':
      description: Foo field description
      fieldPath: '[version=2.0].[type=boolean].field_foo_2'
  name: SampleKafkaDataset
  platform: kafka
  urn: urn:li:dataset:(urn:li:dataPlatform:kafka,SampleKafkaDataset,PROD)
- description: s3 backup of logging events
  fields:
    browser:
      description: test
      fieldPath: browser
    event_data:
      description: Data of your event
      fieldPath: event_data
    event_name:
      description: Name of your logging event
      fieldPath: event_name
    timestamp:
      description: TS the event was ingested
      fieldPath: timestamp
  name: project/root/events/logging_events_bckp
  platform: s3
  urn: urn:li:dataset:(urn:li:dataPlatform:s3,project/root/events/logging_events_bckp,PROD)
