- urn:li:chart:(looker,baz1)
- urn:li:chart:(looker,baz2)
- urn:li:container:5ca904d9fda4a374fd58b9c6b577592d
- urn:li:container:5eafc36baec093a4f45a7ba744978156
- urn:li:container:7e218ab0c48afad26f41aa947f81c847
- urn:li:container:DATABASE
- urn:li:container:SCHEMA
- urn:li:container:eeb1616298fa7519e0072db6e3a393ff
- urn:li:corpGroup:bfoo
- urn:li:corpGroup:jdoe
- urn:li:corpuser:datahub
- urn:li:corpuser:jdoe
- urn:li:dashboard:(looker,baz)
- urn:li:dataFlow:(airflow,dag_abc,PROD)
- urn:li:dataJob:(urn:li:dataFlow:(airflow,dag_abc,PROD),task_123)
- urn:li:dataJob:(urn:li:dataFlow:(airflow,dag_abc,PROD),task_456)
- urn:li:dataset:(urn:li:dataPlatform:exasol,realestate_db.sales,PROD)
- urn:li:dataset:(urn:li:dataPlatform:hdfs,SampleHdfsDataset,PROD)
- urn:li:dataset:(urn:li:dataPlatform:hive,SampleHiveDataset,PROD)
- urn:li:dataset:(urn:li:dataPlatform:hive,fct_users_created,PROD)
- urn:li:dataset:(urn:li:dataPlatform:hive,fct_users_deleted,PROD)
- urn:li:dataset:(urn:li:dataPlatform:hive,logging_events,PROD)
- urn:li:dataset:(urn:li:dataPlatform:kafka,SampleKafkaDataset,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,datahub.metadata_aspect_v2,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.ADMINISTRABLE_ROLE_AUTHORIZATIONS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.APPLICABLE_ROLES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.CHARACTER_SETS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.CHECK_CONSTRAINTS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.COLLATIONS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.COLLATION_CHARACTER_SET_APPLICABILITY,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.COLUMNS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.COLUMNS_EXTENSIONS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.COLUMN_PRIVILEGES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.COLUMN_STATISTICS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.ENABLED_ROLES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.ENGINES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.EVENTS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_BUFFER_PAGE,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_BUFFER_PAGE_LRU,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_BUFFER_POOL_STATS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_CACHED_INDEXES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_CMP,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_CMPMEM,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_CMPMEM_RESET,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_CMP_PER_INDEX,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_CMP_PER_INDEX_RESET,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_CMP_RESET,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_COLUMNS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_DATAFILES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_FIELDS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_FOREIGN,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_FOREIGN_COLS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_FT_BEING_DELETED,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_FT_CONFIG,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_FT_DEFAULT_STOPWORD,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_FT_DELETED,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_FT_INDEX_CACHE,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_FT_INDEX_TABLE,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_INDEXES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_METRICS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_SESSION_TEMP_TABLESPACES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_TABLES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_TABLESPACES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_TABLESPACES_BRIEF,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_TABLESTATS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_TEMP_TABLE_INFO,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_TRX,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.INNODB_VIRTUAL,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.KEYWORDS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.KEY_COLUMN_USAGE,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.OPTIMIZER_TRACE,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.PARAMETERS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.PARTITIONS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.PLUGINS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.PROCESSLIST,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.PROFILING,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.REFERENTIAL_CONSTRAINTS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.RESOURCE_GROUPS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.ROLE_COLUMN_GRANTS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.ROLE_ROUTINE_GRANTS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.ROLE_TABLE_GRANTS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.ROUTINES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.SCHEMATA,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.SCHEMATA_EXTENSIONS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.SCHEMA_PRIVILEGES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.STATISTICS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.ST_GEOMETRY_COLUMNS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.ST_SPATIAL_REFERENCE_SYSTEMS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.ST_UNITS_OF_MEASURE,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.TABLES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.TABLESPACES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.TABLESPACES_EXTENSIONS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.TABLES_EXTENSIONS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.TABLE_CONSTRAINTS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.TABLE_CONSTRAINTS_EXTENSIONS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.TABLE_PRIVILEGES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.TRIGGERS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.USER_ATTRIBUTES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.USER_PRIVILEGES,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.VIEWS,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.VIEW_ROUTINE_USAGE,PROD)
- urn:li:dataset:(urn:li:dataPlatform:mysql_sqlalchemy,information_schema.VIEW_TABLE_USAGE,PROD)
- urn:li:dataset:(urn:li:dataPlatform:s3,project/root/events/logging_events_bckp,PROD)
- urn:li:glossaryNode:ClientsAndAccounts
- urn:li:glossaryTerm:AccountBalance
- urn:li:glossaryTerm:CustomerAccount
- urn:li:glossaryTerm:SavingAccount
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_BOOL_LIST_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_BOOL_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_BYTES_LIST_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_BYTES_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_DOUBLE_LIST_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_DOUBLE_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_FLOAT_LIST_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_FLOAT_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_INT32_LIST_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_INT32_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_INT64_LIST_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_INT64_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_STRING_LIST_feature)
- urn:li:mlFeature:(test_feature_table_all_feature_dtypes,test_STRING_feature)
- urn:li:mlFeature:(test_feature_table_no_labels,test_BYTES_feature)
- urn:li:mlFeature:(test_feature_table_single_feature,test_BYTES_feature)
- urn:li:mlFeature:(user_analytics,date_joined)
- urn:li:mlFeature:(user_features,is_premium_user)
- urn:li:mlFeature:(user_features,number_of_visits)
- urn:li:mlFeature:(user_features,regions)
- urn:li:mlFeatureTable:(urn:li:dataPlatform:feast,test_feature_table_all_feature_dtypes)
- urn:li:mlFeatureTable:(urn:li:dataPlatform:feast,test_feature_table_no_labels)
- urn:li:mlFeatureTable:(urn:li:dataPlatform:feast,test_feature_table_single_feature)
- urn:li:mlFeatureTable:(urn:li:dataPlatform:feast,user_analytics)
- urn:li:mlFeatureTable:(urn:li:dataPlatform:feast,user_features)
- urn:li:mlModel:(urn:li:dataPlatform:science,scienceModel,PROD)
- urn:li:mlPrimaryKey:(test_feature_table_all_feature_dtypes,dummy_entity_1)
- urn:li:mlPrimaryKey:(test_feature_table_all_feature_dtypes,dummy_entity_2)
- urn:li:mlPrimaryKey:(test_feature_table_no_labels,dummy_entity_2)
- urn:li:mlPrimaryKey:(test_feature_table_single_feature,dummy_entity_1)
- urn:li:mlPrimaryKey:(user_analytics,user_name)
- urn:li:mlPrimaryKey:(user_features,user_id)
- urn:li:mlPrimaryKey:(user_features,user_name)
- urn:li:tag:Legacy
- urn:li:tag:NeedsDocumentation
